//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jonghor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Reserved
    {
        public string Username { get; set; }
        public int Room_ID { get; set; }
        public int Count { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Room Room { get; set; }
    }
}
